export type Tools =
    "Bold"
    | "Emoji"
    | "Blockquote"
    | "Code"
    | "CodeBlock"
    | "Heading"
    | "Highlight"
    | "Italic"
    | "Link"
    | "OrderList"
    | "TaskList"
    | "Subscript"
    | "Superscript"
    | "Table"
    | "TextAlign"
    | "Underline"
